apiVersion: v1
kind: Service
metadata: 
  name: backend-svc
  labels:
    name: backend-svc
    app: capitec-user-service
spec:
  type: ClusterIP
  ports:
  - targetPort: 8080
    port: 8080
  selector:
    name: backend-pod
    app: capitec-user-svc