apiVersion: v1
kind: Service
metadata: 
  name: frontend-svc
  labels:
    name: frontend-svc
    app: capitec-user-service
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 4200
    nodePort: 30004
  selector:
    name: frontend-pod
    app: capitec-user-service