apiVersion: v1
kind: Service
metadata: 
  name: postgres-svc
  labels:
    app: capitec-user-service
    name: postgres-svc
spec:
  type: ClusterIP
  ports:
  - targetPort: 5432
    port: 5432
  selector:
    name: postgres-pod
    app: capitec-user-service