apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deploy
  labels: 
    name: postgres-deploy
    app: capitec-user-service
spec:
  template:
    metadata: 
        name: postgres-pod
        labels:
          name: postgres-pod
          app: capitec-user-service
    spec: 
        containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
  replicas: 2
  selector: 
    matchLabels:
      name: postgres-pod
      app: capitec-user-service
  strategy:
    type: RollingUpdate